# Generated by Django 5.1.4 on 2025-01-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resulttable',
            old_name='name',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='coordinatortable',
            name='category',
        ),
        migrations.AddField(
            model_name='coordinatortable',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
