# Generated by Django 5.1.4 on 2025-01-08 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_rename_username_logintable_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatortable',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
