# Generated by Django 5.1.3 on 2025-01-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_coordinatortable_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votertable',
            name='password',
        ),
        migrations.RemoveField(
            model_name='votertable',
            name='year',
        ),
        migrations.AddField(
            model_name='logintable',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
