# Generated by Django 5.1.3 on 2025-01-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_votertable_password_remove_votertable_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votertable',
            name='otp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
