# Generated by Django 5.1.3 on 2025-01-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_votertable_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='votertable',
            name='voter_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='votertable',
            name='voter_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('vote_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.candidatetable')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator.votertable')),
            ],
        ),
    ]
