# Generated by Django 5.1.3 on 2025-01-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_votertable_voter_id_alter_votertable_voter_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votertable',
            name='known_face_encoding',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
