# Generated by Django 5.1.6 on 2025-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_votertable_known_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetable',
            name='candidate_image',
            field=models.FileField(blank=True, null=True, upload_to='candidate_image'),
        ),
    ]
